// Comprehensive mapping of college abbreviations and short names to full names
const COLLEGE_NAMES: Record<string, string> = {
  // Power 5 Conferences
  "Alabama": "University of Alabama",
  "Arizona": "University of Arizona",
  "Arizona State": "Arizona State University",
  "Auburn": "Auburn University",
  "Baylor": "Baylor University",
  "Boston College": "Boston College",
  "Cal": "University of California, Berkeley",
  "Clemson": "Clemson University",
  "Connecticut": "University of Connecticut",
  "Duke": "Duke University",
  "Florida": "University of Florida",
  "Florida State": "Florida State University",
  "Georgia": "University of Georgia",
  "Georgia Tech": "Georgia Institute of Technology",
  "Illinois": "University of Illinois",
  "Indiana": "Indiana University",
  "Iowa": "University of Iowa",
  "Iowa State": "Iowa State University",
  "Kansas": "University of Kansas",
  "Kansas State": "Kansas State University",
  "Kentucky": "University of Kentucky",
  "Louisville": "University of Louisville",
  "LSU": "Louisiana State University",
  "Maryland": "University of Maryland",
  "Miami": "University of Miami",
  "Michigan": "University of Michigan",
  "Michigan State": "Michigan State University",
  "Minnesota": "University of Minnesota",
  "Mississippi": "University of Mississippi",
  "Missouri": "University of Missouri",
  "NC State": "North Carolina State University",
  "Nebraska": "University of Nebraska",
  "Northwestern": "Northwestern University",
  "Notre Dame": "University of Notre Dame",
  "Ohio State": "Ohio State University",
  "Oklahoma": "University of Oklahoma",
  "Oklahoma State": "Oklahoma State University",
  "Oregon": "University of Oregon",
  "Oregon State": "Oregon State University",
  "Penn State": "Pennsylvania State University",
  "Purdue": "Purdue University",
  "Rutgers": "Rutgers University",
  "South Carolina": "University of South Carolina",
  "Stanford": "Stanford University",
  "Syracuse": "Syracuse University",
  "Tennessee": "University of Tennessee",
  "Texas": "University of Texas at Austin",
  "Texas A&M": "Texas A&M University",
  "Texas Tech": "Texas Tech University",
  "UCLA": "University of California, Los Angeles",
  "UNC": "University of North Carolina",
  "USC": "University of Southern California",
  "Utah": "University of Utah",
  "Vanderbilt": "Vanderbilt University",
  "Virginia": "University of Virginia",
  "Virginia Tech": "Virginia Polytechnic Institute and State University",
  "Washington": "University of Washington",
  "Washington State": "Washington State University",
  "West Virginia": "West Virginia University",
  "Wisconsin": "University of Wisconsin-Madison",

  // Other Notable Programs
  "Boise State": "Boise State University",
  "BYU": "Brigham Young University",
  "Colorado": "University of Colorado Boulder",
  "Colorado State": "Colorado State University",
  "Dayton": "University of Dayton",
  "DePaul": "DePaul University",
  "Drake": "Drake University",
  "East Carolina": "East Carolina University",
  "Evansville": "University of Evansville",
  "Gonzaga": "Gonzaga University",
  "Houston": "University of Houston",
  "Iowa State": "Iowa State University",
  "Marquette": "Marquette University",
  "Memphis": "University of Memphis",
  "Middle Tennessee": "Middle Tennessee State University",
  "New Mexico": "University of New Mexico",
  "New Mexico State": "New Mexico State University",
  "Northern Arizona": "Northern Arizona University",
  "Pepperdine": "Pepperdine University",
  "Saint Louis": "Saint Louis University",
  "San Diego State": "San Diego State University",
  "San Jose State": "San Jose State University",
  "SMU": "Southern Methodist University",
  "Stetson": "Stetson University",
  "Temple": "Temple University",
  "Texas State": "Texas State University",
  "Toledo": "University of Toledo",
  "Tulsa": "University of Tulsa",
  "UNLV": "University of Nevada, Las Vegas",
  "VCU": "Virginia Commonwealth University",
  "Xavier": "Xavier University",

  // Mid-Major Programs
  "Appalachian State": "Appalachian State University",
  "Arkansas": "University of Arkansas",
  "Arkansas State": "Arkansas State University",
  "Ball State": "Ball State University",
  "Belmont": "Belmont University",
  "Bethune-Cookman": "Bethune-Cookman University",
  "Boston University": "Boston University",
  "Bowling Green": "Bowling Green State University",
  "Buffalo": "University at Buffalo",
  "Butler": "Butler University",
  "Campbell": "Campbell University",
  "Central Michigan": "Central Michigan University",
  "Cincinnati": "University of Cincinnati",
  "Cleveland State": "Cleveland State University",
  "Coppin State": "Coppin State University",
  "Cornell": "Cornell University",
  "Creighton": "Creighton University",
  "Delaware": "University of Delaware",
  "Delaware State": "Delaware State University",
  "Detroit Mercy": "University of Detroit Mercy",
  "Drexel": "Drexel University",
  "Eastern Illinois": "Eastern Illinois University",
  "Eastern Kentucky": "Eastern Kentucky University",
  "Eastern Michigan": "Eastern Michigan University",
  "Eastern Washington": "Eastern Washington University",
  "Fairfield": "Fairfield University",
  "Fordham": "Fordham University",
  "George Mason": "George Mason University",
  "George Washington": "George Washington University",
  "Georgetown": "Georgetown University",
  "Grambling": "Grambling State University",
  "Green Bay": "University of Wisconsin-Green Bay",
  "Hawaii": "University of Hawaii",
  "High Point": "High Point University",
  "Howard": "Howard University",
  "Idaho": "University of Idaho",
  "Idaho State": "Idaho State University",
  "Illinois State": "Illinois State University",
  "Incarnate Word": "University of the Incarnate Word",
  "IPFW": "Purdue University Fort Wayne",
  "Iona": "Iona College",
  "Jacksonville": "Jacksonville University",
  "James Madison": "James Madison University",
  "Jacksonville State": "Jacksonville State University",
  "Kent State": "Kent State University",
  "Kennesaw State": "Kennesaw State University",
  "La Salle": "La Salle University",
  "Lamar": "Lamar University",
  "Lehigh": "Lehigh University",
  "Liberty": "Liberty University",
  "Lipscomb": "Lipscomb University",
  "Long Beach State": "California State University, Long Beach",
  "Loyola Marymount": "Loyola Marymount University",
  "Loyola Chicago": "Loyola University Chicago",
  "Maine": "University of Maine",
  "Manhattan": "Manhattan College",
  "Marshall": "Marshall University",
  "Massachusetts": "University of Massachusetts Amherst",
  "McNeese State": "McNeese State University",
  "Merrimack": "Merrimack College",
  "Middle Tennessee State": "Middle Tennessee State University",
  "Milwaukee": "University of Wisconsin-Milwaukee",
  "Mississippi State": "Mississippi State University",
  "Mississippi Valley State": "Mississippi Valley State University",
  "Monmouth": "Monmouth University",
  "Montana": "University of Montana",
  "Montana State": "Montana State University",
  "Morehead State": "Morehead State University",
  "Morgan State": "Morgan State University",
  "Mount St. Mary's": "Mount St. Mary's University",
  "Murray State": "Murray State University",
  "Navy": "United States Naval Academy",
  "Nevada": "University of Nevada, Reno",
  "New Hampshire": "University of New Hampshire",
  "Nicholls State": "Nicholls State University",
  "Norfolk State": "Norfolk State University",
  "North Carolina A&T": "North Carolina A&T State University",
  "North Carolina Central": "North Carolina Central University",
  "North Dakota": "University of North Dakota",
  "North Dakota State": "North Dakota State University",
  "Northern Colorado": "University of Northern Colorado",
  "Northern Illinois": "Northern Illinois University",
  "Northern Kentucky": "Northern Kentucky University",
  "Northern Michigan": "Northern Michigan University",
  "Northeastern": "Northeastern University",
  "Northwestern State": "Northwestern State University",
  "Oakland": "Oakland University",
  "Old Dominion": "Old Dominion University",
  "Oral Roberts": "Oral Roberts University",
  "Penn": "University of Pennsylvania",
  "Portland": "University of Portland",
  "Portland State": "Portland State University",
  "Prairie View A&M": "Prairie View A&M University",
  "Providence": "Providence College",
  "Quinnipiac": "Quinnipiac University",
  "Radford": "Radford University",
  "Rhode Island": "University of Rhode Island",
  "Rice": "Rice University",
  "Richmond": "University of Richmond",
  "Rider": "Rider University",
  "Robert Morris": "Robert Morris University",
  "Samford": "Samford University",
  "San Francisco": "University of San Francisco",
  "Santa Clara": "Santa Clara University",
  "Savannah State": "Savannah State University",
  "Seattle": "Seattle University",
  "Siena": "Siena College",
  "South Alabama": "University of South Alabama",
  "South Dakota": "University of South Dakota",
  "South Dakota State": "South Dakota State University",
  "South Florida": "University of South Florida",
  "Southeast Missouri State": "Southeast Missouri State University",
  "Southern Connecticut": "Southern Connecticut State University",
  "Southern Illinois": "Southern Illinois University Edwardsville",
  "Southern Miss": "University of Southern Mississippi",
  "Southern Utah": "Southern Utah University",
  "Southeastern Louisiana": "Southeastern Louisiana University",
  "Southwestern Louisiana": "University of Louisiana at Lafayette",
  "St. Bonaventure": "St. Bonaventure University",
  "St. Francis": "St. Francis University",
  "St. John's": "St. John's University",
  "St. Joseph's": "Saint Joseph's University",
  "St. Mary's": "Saint Mary's College of California",
  "St. Peter's": "Saint Peter's University",
  "Stanford": "Stanford University",
  "Stephen F. Austin": "Stephen F. Austin State University",
  "Stetson": "Stetson University",
  "Stony Brook": "Stony Brook University",
  "SU New Orleans": "Southern University at New Orleans",
  "Swarthmore": "Swarthmore College",
  "SWAC": "Southwestern Athletic Conference",
  "Tennessee State": "Tennessee State University",
  "Tennessee Tech": "Tennessee Technological University",
  "Texas Arlington": "University of Texas at Arlington",
  "Texas San Antonio": "University of Texas at San Antonio",
  "Texas Southern": "Texas Southern University",
  "The Citadel": "The Citadel, The Military College of South Carolina",
  "Toledo": "University of Toledo",
  "Towson": "Towson University",
  "Troy": "Troy University",
  "Truman State": "Truman State University",
  "UAB": "University of Alabama at Birmingham",
  "UConn": "University of Connecticut",
  "UMBC": "University of Maryland, Baltimore County",
  "UNCG": "University of North Carolina at Greensboro",
  "UNCC": "University of North Carolina at Charlotte",
  "UCSB": "University of California, Santa Barbara",
  "UCSD": "University of California, San Diego",
  "UCSF": "University of California, San Francisco",
  "UIC": "University of Illinois at Chicago",
  "UMass": "University of Massachusetts Amherst",
  "UMKC": "University of Missouri-Kansas City",
  "UMPD": "University of Mount Union",
  "UNI": "University of Northern Iowa",
  "UT Arlington": "University of Texas at Arlington",
  "UT San Antonio": "University of Texas at San Antonio",
  "UT Rio Grande Valley": "University of Texas Rio Grande Valley",
  "Utah State": "Utah State University",
  "Utah Valley": "Utah Valley University",
  "Vermont": "University of Vermont",
  "Villanova": "Villanova University",
  "VMI": "Virginia Military Institute",
  "Wagner": "Wagner College",
  "Wake Forest": "Wake Forest University",
  "Wichita State": "Wichita State University",
  "William & Mary": "College of William & Mary",
  "Wisconsin-Green Bay": "University of Wisconsin-Green Bay",
  "Wisconsin-Milwaukee": "University of Wisconsin-Milwaukee",
  "Wofford": "Wofford College",
  "Wright State": "Wright State University",
  "Wyoming": "University of Wyoming",
  "Yale": "Yale University",
  "Youngstown State": "Youngstown State University",
};

export function getFullCollegeName(collegeName: string | null | undefined): string {
  if (!collegeName) return "";

  // First try exact match
  if (COLLEGE_NAMES[collegeName]) {
    return COLLEGE_NAMES[collegeName];
  }

  // Try case-insensitive match
  const lowerName = collegeName.toLowerCase();
  for (const [key, value] of Object.entries(COLLEGE_NAMES)) {
    if (key.toLowerCase() === lowerName) {
      return value;
    }
  }

  // If no match found, return original name
  return collegeName;
}
